[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="polymorphic-bug-repro"
version="0.0.1"
dependencies=[
    "django==5.2.14",
    "django-polymorphic==4.11.3",
    "pylint==4.0.5",
    "django-stubs==6.0.5",
]

[tool.setuptools]
packages = []

[tool.django-stubs]
django_settings_module = "dpb.settings"
